### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'layer_name'

### ISSUE THREAD

**Issue by karunakar2** [PedroVenancio/export_to_sql_server#5]
****Context:****
the error occurs when the plugin is chained downstream of v.in.wfs.
The idea is to save wfs layers to sql server.

The following error is thrown from SQL
"""
Error encountered while running Export to SQL Server (new connection): Traceback (most recent call last):
File "C:\PROGRA~1/QGIS33~1.10/apps/qgis-ltr/./python/plugins\processing\algs\gdal\GdalAlgorithm.py", line 132, in processAlgorithm
commands = self.getConsoleCommands(parameters, context, feedback, executing=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users/kkint001/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\export_to_sql_server\OgrToSQLServer.py", line 234, in getConsoleCommands
if not input_details.layer_name:
^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'layer_name'
"""

**Comment by karunakar2** [comment]
@PedroVenancio Any thoughts.

**Comment by PedroVenancio** [comment]
@karunakar2 

What versions of QGIS and GDAL are you using? Can you past here the QGIS Help -> About content?

**Comment by karunakar2** [comment]
Hi Pedro I've tried it both on prizren, latest ltr and Lima editions

**Comment by PedroVenancio** [comment]
Can you please upgrade to the latest version 3.38 Grenoble? https://qgis.org/download

**Comment by karunakar2** [comment]
Works with Grenoble, may be good to leave a note about version.
